### ISSUE TITLE
release npm failed

### ISSUE THREAD

**Issue by ThaddeusJiang** [plugoinc/node-common#4]
https://github.com/plugoinc/node-common/actions/runs/6766574989/job/18387888634
![image](https://github.com/plugoinc/node-common/assets/17308201/ba0a8126-6326-4cdb-b579-f440c9890caa)

**Comment by Ko1103** [comment]
これは0.1.1のバージョンを既にpublishしているのに再度別の変更で0.1.1をpublishしようとしてエラーになったパターンですね。
ちょうど天海さんと自分が同じバージョンで変更するMRを二つ作っていて、自分のMRが反映された後に天海さんのMRが反映されたため、このエラーになっています。
